### PR TITLE
update build to 37899

### PR DESCRIPTION
**Pull request by arcaniafr**

### CODE REVIEW

**Comment by Shauren** [comment]
Why did you change the old UF extractor?

**Comment by arcaniafr** [comment]
> Why did you change the old UF extractor?

where is the new uf extractor?

**Comment by Shauren** [comment]
There isn't one. The "new" one is a code generator that must be manually updated by reversing packet structure

**Comment by arcaniafr** [comment]
ok, ty for the informations :) you work on 9.0.5?

**Comment by Shauren** [comment]
Yes, I do

**Pull request closed without merging**
